### ISSUE TITLE
Mapping rules

### ISSUE THREAD

**Issue by nathanatrhea** [RHEAGROUP/DEH-MDSYSML#5]
DST-SYS-SR-0070, DST-SYS-SR-0060, DST-SYS-SR-0050, DST-SYS-SR-0040, DST-SYS-SR-0030
The SysML DST adapter shall support exchange of elements contained in these SysML Diagrams:
 - [x] #17
 - [x] #19
 - [x] #47
 - [x] #48
 - [ ] UseCase -> has been de-scoped 
 - [ ] Parametric -> has been de-scoped 
 - [ ] Activity -> has been de-scoped 
 - [x] State Machine

**Comment by alexatrhea** [comment]
This task indeed need to split out in coordination with Marnix's report.
